name: Labels

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/labeler.yml
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - edited

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  sync-labels:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Sync repository labels
        uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a # v2.3.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/labels.yml
          delete-other-labels: true

  label-pull-requests:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - name: Apply pull request labels
        uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          sync-labels: true
